name: spark_elements
version: 0.0.2
author: Alexander Ewetumo <trinoxf@gmail.com>
description: providing client-side dom components for sparkflow
homepage: http://github.com/influx6/spark-elements.dart
dependencies:
  browser: any
  hub: any
  sparkflow: any
# dependency_overrides:
#   sparkflow:
#     path: ../sparkflow
#   hub:
#     path: ../hub
